### ISSUE TITLE
[BUG] member-ordering-extended with order build-method as overridden-methods

### ISSUE THREAD

**Issue by tsinis** [dart-code-checker/dart-code-metrics-action#110]
* **Dart Code Metrics GitHub Action version: 2.0.0**

**Please show your full configuration:**

You can see the minimal reproducible example with all configs and PR errors at:
https://github.com/tsinis/test_app/runs/7688048394

**What did you do? Please include the source code example causing the issue.**

Code is regular "counter" with initState just for the showcase: https://github.com/tsinis/test_app

**What did you expect to happen?**

DCM Action should not consider the widget's build method as a part of `overridden-methods` if the order rule contains `build-method` already. DCM works perfectly locally:

From the root of the project run:
`flutter pub run dart_code_metrics:metrics analyze lib`
it will return:
`no issues found!`

**What actually happened?**

DCM Action considers build methods as a part of `overridden-methods`

**Are you willing to submit a pull request to fix this bug?**

Not sure tbh., I might take a look if it's Dart-related.

**Comment by tsinis** [comment]
Might be related to https://github.com/dart-code-checker/dart-code-metrics-action/pull/106

**Comment by incendial** [comment]
@tsinis yep, probably, I've pinged @dkrutskikh, waiting for his response

**Comment by tsinis** [comment]
The issue is fixed in https://github.com/dart-code-checker/dart-code-metrics-action/pull/111 thanks, guys!
