### ISSUE TITLE
"No more than 50 items are allowed" encountered

### ISSUE THREAD

**Issue by berkentekin** [dart-code-checker/dart-code-metrics-action#51]
GitHub threw an error when I used this Action with my repository:
> GitHub Error: 
>   Message: Invalid request.
> 
> No more than 50 items are allowed; 125 were supplied.

Is there any way to solve this problem?

**Comment by dkrutskikh** [comment]
@berkentekin please recheck with latest action version

**Comment by berkentekin** [comment]
It works now. Thanks
