### ISSUE TITLE
Ability to add a reply to a pull request

### ISSUE THREAD

**Issue by DevNico** [dart-code-checker/dart-code-metrics-action#67]
Would be great to have the option to get a reply on a pull request with the analysis result!

**Comment by dkrutskikh** [comment]
@DevNico like this https://github.com/dart-code-checker/dart-code-metrics-action/pull/68#issuecomment-987129999 ?

**Comment by DevNico** [comment]
Yes exactly, looks great!

Just to make sure, it would be nice to have this all the time not just on failures.

**Comment by dkrutskikh** [comment]
Available in 1.3.0 release 🚀
