### ISSUE TITLE
[Question] Job Failing with Warnings Reports

### ISSUE THREAD

**Issue by btd1337** [dart-code-checker/dart-code-metrics-action#89]
**What do you want to discuss?**

Github action is failing but just is occurring warnings in the code.

How to change action behavior to fail only when errors occur?

<img width="1290" alt="Captura de Tela 2022-03-04 às 13 24 04" src="https://user-images.githubusercontent.com/11943860/156801020-0e3c5635-e520-4113-8af8-363350995f04.png">

---
**Update**

The problem also happens for Style severity level

<img width="1290" alt="Captura de Tela 2022-03-04 às 13 34 26" src="https://user-images.githubusercontent.com/11943860/156802467-c5fe4c5d-81f3-4a4a-a33c-9bbcfca8042e.png">

**Comment by dkrutskikh** [comment]
@btd1337 in new version we introduce `fatal_warnings`, `fatal_performance` and `fatal_style` parameters for control analyze flow
